<!-- this file was generated by <todo put plugin name> do not edit-->
<script>
  // @ts-nocheck
  // @ts-ignore
  import ViewRestaurant from '$lib//Restaurant/ViewRestaurant.svelte';
  import WriteRestaurant from '$lib/Restaurant/WriteRestaurant.svelte';
  export let Restaurant;
  export let writeFunc;
  export let deleteFunc;
  export let editable = false;
  function toggle() {editable = !editable;}
</script>
{#if Restaurant != null && !editable}
	<ViewRestaurant Restaurant={Restaurant} />
{/if}

{#if  writeFunc != null && !editable }
	<button on:click={writeFunc}> edit </button>
{/if}

<button on:click={deleteFunc}> Delete </button>
