<!-- this file was generated by <todo put plugin name> do not edit-->
<script>
  // @ts-nocheck
  // @ts-ignore
  import ViewRestaurant from '$lib//Restaurant/ViewRestaurant.svelte';
  export let Restaurant;
  export let writeFunc;
  export let deleteFunc;
  let editable = false;

</script>
{#if Restaurant != null }
	<ViewRestaurant Restaurant={Restaurant} />
{/if}

<!-- todo only allow this & delete to be viewable if auth rules permit it.-->
{#if  writeFunc != null && !editable }
	<button on:click={writeFunc}> edit </button>
{/if}

<button on:click={deleteFunc}> Delete </button>
