<!-- this file was generated by <todo put plugin name> do not edit-->
<script>
  // @ts-nocheck
  import EditTakeAwayOptions from "$lib/TakeAwayOptions/EditTakeAwayOptions.svelte";
  export let Restaurant = {};
  if (Restaurant == undefined){ Restaurant = {}}
  function pushtagsArray() {if (Restaurant.tags == undefined) {Restaurant.tags = []};Restaurant.tags = Restaurant.tags.concat("")}
  function removetagsArray(index) {Restaurant.tags.splice(index, 1); Restaurant.tags = Restaurant.tags}
</script>

<div class="Restaurant">
<label for="Restaurant-title"> Restaurant.title </label>
<input class="Restaurant-title" bind:value={Restaurant.title} >
<br><label for="Restaurant-price"> Restaurant.price </label>
<input class="Restaurant-price" type=number bind:value={Restaurant.price} min=0 >
<br><label for="Restaurant-cleanliness"> Restaurant.cleanliness </label>
<select bind:value={Restaurant.cleanliness}>
<option value="CLEANLINESS_UNSPECIFIED">CLEANLINESS_UNSPECIFIED</option>
<option value="CLEANLINESS_DISGUSTING">CLEANLINESS_DISGUSTING</option>
<option value="CLEANLINESS_BAD">CLEANLINESS_BAD</option>
<option value="CLEANLINESS_GOOD">CLEANLINESS_GOOD</option>
<option value="CLEANLINESS_EXCELLENT">CLEANLINESS_EXCELLENT</option>
</select><br>
<label for="tags"> tags </label><br>{#if Restaurant.tags != null}
  {#each Restaurant.tags as tags, key}
    <input class="tags" bind:value={tags} >
    <button on:click={() => removetagsArray(key)}> Remove from tags</button><br>
  {/each}
{/if}
<button on:click={pushtagsArray}> Add to tags</button>
<EditTakeAwayOptions bind:TakeAwayOptions={Restaurant.takeAway} />
</div>

