<!-- this file was generated by <todo put plugin name> do not edit-->
<script>
  // @ts-nocheck
  import ViewTakeAwayOptions from "$lib/TakeAwayOptions/ViewTakeAwayOptions.svelte";
  export let Restaurant = {};
</script>

<div class="Restaurant">
<p class="Restaurant.title"> Restaurant.title : {Restaurant.title} </p>
<p class="Restaurant.price"> Restaurant.price : {Restaurant.price} </p>
<p class="Restaurant.cleanliness"> Restaurant.cleanliness : {Restaurant.cleanliness} </p>
{#if Restaurant.tags != null}
  {#each Restaurant.tags as tags}
    <p class="tags"> tags : {tags} </p>
  {/each}
{/if}
<ViewTakeAwayOptions TakeAwayOptions={Restaurant.takeAway} />
</div>

