<!-- this file was generated by <todo put plugin name> do not edit-->
<script>
  // @ts-nocheck
  // @ts-ignore
  import ViewTakeAwayOptions from '$lib//TakeAwayOptions/ViewTakeAwayOptions.svelte';
  import WriteTakeAwayOptions from '$lib/TakeAwayOptions/WriteTakeAwayOptions.svelte';
  export let TakeAwayOptions;
  export let writeFunc;
  export let deleteFunc;
  export let editable = false;
  function toggle() {editable = !editable;}
</script>
{#if TakeAwayOptions != null && !editable}
	<ViewTakeAwayOptions TakeAwayOptions={TakeAwayOptions} />
{/if}

{#if  writeFunc != null && !editable }
	<button on:click={writeFunc}> edit </button>
{/if}

<button on:click={deleteFunc}> Delete </button>
