<!-- this file was generated by <todo put plugin name> do not edit-->
<script>
  // @ts-nocheck
  export let TakeAwayOptions = {};
  if (TakeAwayOptions == undefined){ TakeAwayOptions = {}}
</script>

<div class="TakeAwayOptions">
<label for="TakeAwayOptions.pickup"> TakeAwayOptions.pickup </label>
<input class="TakeAwayOptions.pickup" type=checkbox  bind:checked={TakeAwayOptions.pickup}>
<br><label for="TakeAwayOptions.phone"> TakeAwayOptions.phone </label>
<input class="TakeAwayOptions.phone" type=checkbox  bind:checked={TakeAwayOptions.phone}>
<br><label for="TakeAwayOptions.uber"> TakeAwayOptions.uber </label>
<input class="TakeAwayOptions.uber" type=checkbox  bind:checked={TakeAwayOptions.uber}>
<br><label for="TakeAwayOptions.doorDash"> TakeAwayOptions.doorDash </label>
<input class="TakeAwayOptions.doorDash" type=checkbox  bind:checked={TakeAwayOptions.doorDash}>
<br>
</div>

