<!-- this file was generated by <todo put plugin name> do not edit-->
<script>
  // @ts-nocheck
  export let TakeAwayOptions = {};
</script>

<p> TakeAwayOptions.pickup : {TakeAwayOptions.pickup}  </p>

<p> TakeAwayOptions.phone : {TakeAwayOptions.phone}  </p>

<p> TakeAwayOptions.uber : {TakeAwayOptions.uber}  </p>

<p> TakeAwayOptions.doorDash : {TakeAwayOptions.doorDash}  </p>

